sudo: required
service:
    - docker

before_install:
  - docker build -t abdulbasitnawab/docker-react -f Dockerfile.dev .

script:
  - docker run abdulbasitnawab/docker-react npm run test -- -- coverage